version: '3'
services:
  mysql:
   image: mysql:latest
   container_name: mysql
   ports:
    - 3307:3306
   restart: always 
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: test
    MYSQL_HOST: mysql
    MYSQL_PASSWORD: root

  app:
    depends_on:
     - mysql
    image: docker.io/rtppoc/node-js  
    links:
      - mysql
    ports:
      - 3000:3000
    restart: always
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQLPASSWORD: root
       MYSQL_DB: db  
     
     