services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: letmein
      DB_NAME: test
      DB_CONNECTION_LIMIT: 20
      SERVER_PORT: 8000
    depends_on:
      - mysqldb
    networks:
      - internalnet    

networks:
  internalnet:
    driver: bridge