version: '3'
services:
  mysql:
   container_name: mysqldb
   image: mysql:latest
   ports:
    - 3307:3306
   restart: always 
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: test

  app:
    
    build: .
    restart: always
    container_name: node_application 
    ports:
      - 3000:3000
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQLPASSWORD: 123456
       MYSQL_PORT: 3306  
     
     