version: '3'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    
  api:
    build: .
    ports:
      - 9000:9000
    environment:
      PORT: 9000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db
